services:
  n8n:
    container_name: n8n-server
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ./data:/root/.n8n
      - ./files:/files
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  
  # If you're running your own external PostgreSQL instance, you can comment out this service
  postgres:
    container_name: n8n-db
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
